### PR TITLE
[coro_rpc] Full MSVC support and bug fixes part 1.

### LINKED ISSUE #18: Support msvc
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/yalantinglibs/issues) and found no similar issues.

### What happened + What you expected to happen
easylog compile failed with msvc, should be fixed.

### Reproduction way
build with msvc2022

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by refvalue**
## Why

Closes #18 
Made this repo available to MSVC part 1.

## What is changing

Added:
- util/magic_names.hpp
- util/meta_string.hpp
- A uniform MSVC/GCC/Clang implementation of reflecting qualified function names.
- A meta_string class for template programming as non-type parameter when enabling C++20.

Added:
- util/benchmark
- util/examples
- util/tests
Some static asserts for ensuring correctness of newly added code.

Modified/Fixed:
- coro_rpc: CMakeLists.txt
- coro_rpc/tests/ServerTester.hpp
- coro_rpc/tests/test_coro_rpc_server.hpp
- util/function_name.h
- .gitignore
Fixed fatal issues when compiling with MSVC.
Fixed incorrect function names when using MSVC.
Added .gitignore items for .vs/out folders.

All unit tests have passed on MSVC 19.3x/GCC11.x/12.x/Clang 15+.
Core logics have passed on GoldBolt.

## Example
Please view src/util/tests

### CODE REVIEW

**Comment by refvalue** [comment]
@PikachuHyA Please review. Appreciate.

**Comment by qicosmos** [comment]
MacOS lack of std::ranges support, you could replace std::range with STL algorithm.

**Comment by poor-circle** [comment]
```
/Users/runner/work/yalantinglibs/yalantinglibs/include/util/meta_string.hpp:118:46: error: invalid operands to binary expression ('std::string_view' (aka 'basic_string_view<char>') and 'std::string_view')
  return static_cast<std::string_view>(left) <=>
```
It seems that Apple Clang don‘t implement the operator<=> in std::string_view……
For workaround, could we just remove it?

**Comment by refvalue** [comment]
> MacOS lack of std::ranges support, you could replace std::range with STL algorithm.

OK. I have fixed this. Apple Clang complained no support for the spaceship operator and I am working around it.

**Comment by refvalue** [comment]
> ```
> /Users/runner/work/yalantinglibs/yalantinglibs/include/util/meta_string.hpp:118:46: error: invalid operands to binary expression ('std::string_view' (aka 'basic_string_view<char>') and 'std::string_view')
>   return static_cast<std::string_view>(left) <=>
> ```
> 
> It seems that Apple Clang don‘t implement the operator<=> in std::string_view…… For workaround, could we just remove it?

Emmm... a broken heart.. lol  I'm working in process for it.

**Comment by poor-circle** [comment]
It seems thar the Clang14 in Ubuntu 20.04 crashed.
```
[ 98%] Building CXX object src/util/tests/CMakeFiles/util_tests.dir/static_asserts.cpp.o
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/bin/clang++ -I/home/runner/work/yalantinglibs/yalantinglibs/include -O3 -DNDEBUG -std=gnu++20 -MD -MT src/util/tests/CMakeFiles/util_tests.dir/static_asserts.cpp.o -MF CMakeFiles/util_tests.dir/static_asserts.cpp.o.d -o CMakeFiles/util_tests.dir/static_asserts.cpp.o -c /home/runner/work/yalantinglibs/yalantinglibs/src/util/tests/static_asserts.cpp
1.	/home/runner/work/yalantinglibs/yalantinglibs/src/util/tests/static_asserts.cpp:77:1: current parser token 'void'
2.	/home/runner/work/yalantinglibs/yalantinglibs/src/util/tests/static_asserts.cpp:4:1: parsing namespace 'refvalue'
3.	/home/runner/work/yalantinglibs/yalantinglibs/src/util/tests/static_asserts.cpp:5:26: parsing function body 'refvalue::tests::meta_string_tests'
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
/lib/x86_64-linux-gnu/libLLVM-14.so.1(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamEi+0x31)[0x7f333812ad01]
/lib/x86_64-linux-gnu/libLLVM-14.so.1(_ZN4llvm3sys17RunSignalHandlersEv+0xee)[0x7f3338128a3e]
/lib/x86_64-linux-gnu/libLLVM-14.so.1(_ZN4llvm3sys15CleanupOnSignalEm+0xfb)[0x7f333812a0ab]
/lib/x86_64-linux-gnu/libLLVM-14.so.1(+0xd6bdff)[0x7f3338056dff]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f3336dd2520]
/lib/x86_64-linux-gnu/libc.so.6(free+0x69)[0x7f3336e354c9]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(+0x1[127](https://github.com/alibaba/yalantinglibs/actions/runs/3375003050/jobs/5601226001#step:5:128)671)[0x7f333ece4671]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang4Sema30PopExpressionEvaluationContextEv+0x7ce)[0x7f333ef9b5be]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang4Sema23ActOnFinishFunctionBodyEPNS_4DeclEPNS_4StmtEb+0x1a32)[0x7f333ee54c62]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser26ParseFunctionStatementBodyEPNS_4DeclERNS0_10ParseScopeE+0x118)[0x7f333e668878]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser23ParseFunctionDefinitionERNS_17ParsingDeclaratorERKNS0_18ParsedTemplateInfoEPNS0_18LateParsedAttrListE+0xddf)[0x7f333e68259f]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser14ParseDeclGroupERNS_15ParsingDeclSpecENS_17DeclaratorContextEPNS_14SourceLocationEPNS0_12ForRangeInitE+0x1210)[0x7f333e5dacc0]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser30ParseDeclOrFunctionDefInternalERNS_25ParsedAttributesWithRangeERNS_15ParsingDeclSpecENS_15AccessSpecifierE+0x35b)[0x7f333e6815ab]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser36ParseDeclarationOrFunctionDefinitionERNS_25ParsedAttributesWithRangeEPNS_15ParsingDeclSpecENS_15AccessSpecifierE+0x190)[0x7f333e681060]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser24ParseExternalDeclarationERNS_25ParsedAttributesWithRangeEPNS_15ParsingDeclSpecE+0x92a)[0x7f333e6804da]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser19ParseInnerNamespaceERKN4llvm11SmallVectorINS0_18InnerNamespaceInfoELj4EEEjRNS_14SourceLocationERNS_16ParsedAttributesERNS_24BalancedDelimiterTrackerE+0xbc)[0x7f333e5eecbc]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser19ParseInnerNamespaceERKN4llvm11SmallVectorINS0_18InnerNamespaceInfoELj4EEEjRNS_14SourceLocationERNS_16ParsedAttributesERNS_24BalancedDelimiterTrackerE+0x1b5)[0x7f333e5eedb5]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser14ParseNamespaceENS_17DeclaratorContextERNS_14SourceLocationES2_+0x14b9)[0x7f333e5ee809]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser16ParseDeclarationENS_17DeclaratorContextERNS_14SourceLocationERNS_25ParsedAttributesWithRangeEPS2_+0x41e)[0x7f333e5d488e]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser24ParseExternalDeclarationERNS_25ParsedAttributesWithRangeEPNS_15ParsingDeclSpecE+0xc4)[0x7f333e67fc74]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6Parser17ParseTopLevelDeclERNS_9OpaquePtrINS_12DeclGroupRefEEEb+0x3ad)[0x7f333e67eb1d]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang8ParseASTERNS_4SemaEbb+0x2fd)[0x7f333e5c18ed]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang13CodeGenAction13ExecuteActionEv+0xb1)[0x7f333f735b71]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang14FrontendAction7ExecuteEv+0x67)[0x7f33400d1b57]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x336)[0x7f33400293a6]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0x29b)[0x7f334014b45b]
/usr/bin/clang++(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x99b)[0x4[132](https://github.com/alibaba/yalantinglibs/actions/runs/3375003050/jobs/5601226001#step:5:133)8b]
/usr/bin/clang++[0x4114bc]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(+0x20eaed2)[0x7f333fca7ed2]
/lib/x86_64-linux-gnu/libLLVM-14.so.1(_ZN4llvm20CrashRecoveryContext9RunSafelyENS_12function_refIFvvEEE+0xdd)[0x7f3338056b6d]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZNK5clang6driver10CC1Command7ExecuteEN4llvm8ArrayRefINS2_8OptionalINS2_9StringRefEEEEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPb+0x140)[0x7f333fca79c0]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZNK5clang6driver11Compilation14ExecuteCommandERKNS0_7CommandERPS3_+0x3f3)[0x7f333fc72183]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZNK5clang6driver11Compilation11ExecuteJobsERKNS0_7JobListERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0x8a)[0x7f333fc7240a]
/lib/x86_64-linux-gnu/libclang-cpp.so.14(_ZN5clang6driver6Driver18ExecuteCompilationERNS0_11CompilationERN4llvm15SmallVectorImplISt4pairIiPKNS0_7CommandEEEE+0x1a7)[0x7f333fc8c507]
/usr/bin/clang++(main+0x2816)[0x410f26]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f3336db9d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f3336db9e40]
/usr/bin/clang++(_start+0x25)[0x40e3b5]
clang: error: clang frontend command failed with exit code [139](https://github.com/alibaba/yalantinglibs/actions/runs/3375003050/jobs/5601226001#step:5:140) (use -v to see invocation)
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: note: diagnostic msg: 
********************
```

**Comment by poor-circle** [comment]
See : [https://godbolt.org/z/1qzfT64nr](godblot)
Crashed in Clang 14.0.0 & 12.0.0
Passed in Clang 15.0.0,13.0.1,12.0.1 & 12.0.0

**Comment by refvalue** [comment]
> See : [godbolt](https://godbolt.org/z/1qzfT64nr) Crashed in Clang 14.0.0 & 12.0.0 Passed in Clang 15.0.0,13.0.1,12.0.1 & 12.0.0

Appreciate your tests and I found x86-64 Clang crashed when there were too many ```static constexpr``` variables... and after removing the ```static``` token it compiled.

**Comment by poor-circle** [comment]
> > See : [godbolt](https://godbolt.org/z/1qzfT64nr) Crashed in Clang 14.0.0 & 12.0.0 Passed in Clang 15.0.0,13.0.1,12.0.1 & 12.0.0
> 
> Appreciate your tests and I found x86-64 Clang crashed when there were too many `static constexpr` variables... and after removing the `static` token it compiled.

It's not the problem of `static constexpr` variables...

See [This simpifly example](https://godbolt.org/z/d86n1EPEf)

**Comment by refvalue** [comment]
> > > See : [godbolt](https://godbolt.org/z/1qzfT64nr) Crashed in Clang 14.0.0 & 12.0.0 Passed in Clang 15.0.0,13.0.1,12.0.1 & 12.0.0
> > 
> > 
> > Appreciate your tests and I found x86-64 Clang crashed when there were too many `static constexpr` variables... and after removing the `static` token it compiled.
> 
> It's not the problem of `static constexpr` variables...
> 
> See [This simpifly example](https://godbolt.org/z/d86n1EPEf)

Ummm... I see, thanks.I tested [this workaround](https://godbolt.org/z/Y1eze737Y) and the designated Clang version passed my code.

**Comment by poor-circle** [comment]
> > > > See : [godbolt](https://godbolt.org/z/1qzfT64nr) Crashed in Clang 14.0.0 & 12.0.0 Passed in Clang 15.0.0,13.0.1,12.0.1 & 12.0.0
> > > 
> > > 
> > > Appreciate your tests and I found x86-64 Clang crashed when there were too many `static constexpr` variables... and after removing the `static` token it compiled.
> > 
> > 
> > It's not the problem of `static constexpr` variables...
> > See [This simpifly example](https://godbolt.org/z/d86n1EPEf)
> 
> Ummm... I see, thanks.I tested [this workaround](https://godbolt.org/z/Y1eze737Y) and the designated Clang version passed my code.

LGTM

**Comment by poor-circle** [comment]
Created an [issue](https://github.com/llvm/llvm-project/issues/58753) to LLVM.

**Comment by poor-circle** [comment]
Some assertion failed in clang14 debug mode.

```
/home/runner/work/yalantinglibs/yalantinglibs/src/util/tests/static_asserts.cpp:118:3: error: static_assert failed due to requirement 'qualified_name_of_v<&func_template<int, double>> == refvalue::meta_string<58>{"refvalue::tests::ns1::ns2::ns3::func_template<int, double>"}'
  static_assert(
  ^
/home/runner/work/yalantinglibs/yalantinglibs/src/util/tests/static_asserts.cpp:135:3: error: static_assert failed due to requirement 'name_of_v<&func_template<int, double>> == refvalue::meta_string<26>{"func_template<int, double>"}'
  static_assert(name_of_v<&func_template<int, double>> ==
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by refvalue** [comment]
> ~

Got it. I am writing some cases to make sure what the signature of a function template is.

**Comment by refvalue** [comment]
> Some assertion failed in clang14 debug mode.
> 
> ```
> /home/runner/work/yalantinglibs/yalantinglibs/src/util/tests/static_asserts.cpp:118:3: error: static_assert failed due to requirement 'qualified_name_of_v<&func_template<int, double>> == refvalue::meta_string<58>{"refvalue::tests::ns1::ns2::ns3::func_template<int, double>"}'
>   static_assert(
>   ^
> /home/runner/work/yalantinglibs/yalantinglibs/src/util/tests/static_asserts.cpp:135:3: error: static_assert failed due to requirement 'name_of_v<&func_template<int, double>> == refvalue::meta_string<26>{"func_template<int, double>"}'
>   static_assert(name_of_v<&func_template<int, double>> ==
>   ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

Got it. I am writing some cases to make sure what the signature of a function template is.

File: include/util/meta_string.hpp [hunk 1]
```diff
@@ -0,0 +1,238 @@
...
+#include <compare>
+#include <concepts>
+#include <cstddef>
+#include <span>
+#include <string_view>
+#include <utility>
+
+namespace refvalue {
+template <std::size_t N>
+struct meta_string {
```
Comment (qicosmos) [inline include/util/meta_string.hpp:34]: lack of concat function and operator +

File: src/coro_rpc/tests/ServerTester.hpp [hunk 2]
```diff
@@ -319,7 +319,11 @@ struct ServerTester : TesterConfig {
 
   template <auto func, typename... Args>
   void test_call_with_delay_func_client_read_length_error(Args... args) {
+#ifdef _MSC_VER
```
Comment (qicosmos) [inline src/coro_rpc/tests/ServerTester.hpp:322]: please extract the code into a function to avoid duplicate code.

File: include/util/meta_string.hpp (hunk 1 above)
Comment (qicosmos) [reply include/util/meta_string.hpp:34]: a data() member function is also needed.

**Comment by qicosmos** [comment]
__PRETTY_FUNCTION__ does not contain template function arguments symbols, only contain function name, so i think we can't support template rpc function now, and i think it is acceptable.

So remove template function test case is fine.

**Comment by qicosmos** [comment]
I find a solution to support template function, i will improve this pr :)

**Comment by poor-circle** [comment]
> I find a solution to support template function, i will improve this pr :)

Can we merge this PR first, and add it later?

File: include/util/meta_string.hpp (hunk 1 above)
Comment (refvalue) [reply include/util/meta_string.hpp:34]: > **PRETTY_FUNCTION** does not contain template function arguments symbols, only contain function name, so i think we can't support template rpc function now, and i think it is acceptable.
> 
> So remove template function test case is fine.

OK. I have implemented a new version of uniform output without template arguments.

**Comment by refvalue** [comment]
> I find a solution to support template function, i will improve this pr :)

Perfect; welcome to improve this code. lol

**Comment by PikachuHyA** [comment]
@refvalue please check these failed tests

https://github.com/alibaba/yalantinglibs/actions/runs/3383985039/jobs/5620424487

**Comment by refvalue** [comment]
> @refvalue please check these failed tests
> 
> https://github.com/alibaba/yalantinglibs/actions/runs/3383985039/jobs/5620424487

Alright. I am reviewing the report.

**Comment by PikachuHyA** [comment]
> Alright. I am reviewing the report.

@refvalue After you fixed all failed tests. I will rerun CIs.

**Comment by refvalue** [comment]
@PikachuHyA Emm... Sorry but the issue still exists...I will make a full test on x86 architecture to resolve this.

**Comment by poor-circle** [comment]
Is it only failed in x86? May be we can add it's support in next PR.

**Comment by poor-circle** [comment]
hmm, the test is timeout?
https://github.com/alibaba/yalantinglibs/actions/runs/3386262607/jobs/5625436568

**Comment by refvalue** [comment]
> @refvalue please check these failed tests
> 
> https://github.com/alibaba/yalantinglibs/actions/runs/3383985039/jobs/5620424487



> hmm, the test is timeout? https://github.com/alibaba/yalantinglibs/actions/runs/3386262607/jobs/5625436568

Yeah..it seems that there are some issues on the lifetimes of io_context and coro test calls. I will try resolving them today.

**Comment by qicosmos** [comment]
> > @refvalue please check these failed tests
> > https://github.com/alibaba/yalantinglibs/actions/runs/3383985039/jobs/5620424487
> 
> > hmm, the test is timeout? https://github.com/alibaba/yalantinglibs/actions/runs/3386262607/jobs/5625436568
> 
> Yeah..it seems that there are some issues on the lifetimes of io_context and coro test calls. I will try resolving them today.

No hurry, i will look at the failed cases at this weekend, maybe because of temporary variable life time when call rpc.

**Comment by refvalue** [comment]
> > > @refvalue please check these failed tests
> > > https://github.com/alibaba/yalantinglibs/actions/runs/3383985039/jobs/5620424487
> > 
> > 
> > > hmm, the test is timeout? https://github.com/alibaba/yalantinglibs/actions/runs/3386262607/jobs/5625436568
> > 
> > 
> > Yeah..it seems that there are some issues on the lifetimes of io_context and coro test calls. I will try resolving them today.
> 
> No hurry, i will look at the failed cases at this weekend, maybe because of temporary variable life time when call rpc.

Fine.

**Comment by qicosmos** [comment]
Could you rebase the branch: fix_for_msvc?

**Comment by refvalue** [comment]
> Could you rebase the branch: fix_for_msvc?

Sure. I'll rebase my local branch.

**Comment by qicosmos** [comment]
Not ready

> 

Do it later, not ready now.

**Comment by qicosmos** [comment]
There is a bug in asio on windows, we can continue support msvc after fixing the bug.
But your PR can be merged firstly, please rebase main, i will merge this PR.

**Comment by refvalue** [comment]
> There is a bug in asio on windows, we can continue to support msvc after fixing the bug. But your PR can be merged firstly, please rebase main, i will merge this PR. @refvalue

Perfect. I'll finish rebasing tonight.

**Comment by qicosmos** [comment]
MSVC CI passed without ssl, we will fix ssl in next PR, thanks for your PR @refvalue

**Review by qicosmos — APPROVED** [review]
LGTM

**Comment by refvalue** [comment]
> MSVC CI passed without ssl, we will fix ssl in next PR, thanks for your PR @refvalue

No problem. My pleasure to contribute code to the Community.

**Comment by qicosmos** [comment]
@refvalue could you also provide a c++17 version magic name?Because some one need to compile it with gcc8.3.
